<?php
return [
    'Admisi dan Billing',
    'Akuntansi',
    'Casemix',
    'CSSD',
    'Direktur RS',
    'Dokter',
    'Farmasi',
    'Fisioterapi',
    'Gudang',
    'Gizi',
    'HD',
    'ICU',
    'IT',
    'Kesehatan Lingkungan',
    'Kanit',
    'Keuangan',
    'Komite Medik',
    'Komite Mutu',
    'Laboratorium',
    'Marketing',
    'Manager',
    'Maintenance',
    'NICU dan PICU',
    'NS Poli',
    'OK',
    'Pengadaan',
    'Perawat',
    'Rawat Inap',
    'Radiologi',
    'Rekam Medis',
    'Sekretaris',
    'Security',
    'SDM',
    'SPV',
    'UGD',
    'VK',
];
