<?php

return [
    'units' => [
        'Admisi dan Billing',
        'Akuntansi',
        'Casemix',
        'CSSD',
        'Direktur RS',
        'Dokter',
        'Farmasi',
        'Fisioterapi',
        'Gudang',
        'Gizi',
        'HD',
        'ICU',
        'IT',
        'Kesehatan Lingkungan',
        'Kanit',
        'Keuangan',
        'Komite Medik',
        'Komite Mutu',
        'Laboratorium',
        'Marketing',
        'Manager',
        'Maintenance',
        'NICU dan PICU',
        'NS Poli',
        'OK',
        'Pengadaan',
        'Perawat',
        'Rawat Inap',
        'Radiologi',
        'Rekam Medis',
        'Sekretaris',
        'Security',
        'SDM',
        'SPV',
        'UGD',
        'VK',
    ],

    'spo' => [
        'Asuhan Mutu',
        'Div. Akuntansi',
        'Div. Keuangan',
        'Div. HLC',
        'Duty Manajer',
        'Div. Teknologi Informasi',
        'Dept. Casemix',
        'Dept. Penunjang Medis',
        'Dept. SDM & Hukum',
        'Dept. Pelayanan Medis',
        'Dialisis',
        'Farmasi',
        'Gizi',
        'IGD',
        'Intensif',
        'Kamar Operasi & CSSD',
        'Komite Etik & Hukum',
        'Komite Keperawatan',
        'Komite Medik',
        'Komite Mutu',
        'Komite PPI',
        'Komite PPRA',
        'Komite Nakes Lain',
        'Komite K3RS',
        'Komite Farmasi Terapi',
        'Laboratorium',
        'Layanan Pelanggan',
        'Logistik & Pengembangan',
        'Pemeliharaan',
        'Pemasaran',
        'Pengadaan & Aset',
        'Poliklinik',
        'Rawat Inap',
        'Radiologi',
        'Rehabilitasi Medik',
        'Rekam Medik',
        'Ruang Bersalin',
        'Tata Graha',
    ],

    'perawat' => [
        'Yusuf Ifnugroho, AMK">Yusuf Ifnugroho, AMK',
        'Nur Fitriyana Sutisna, S.Kep.,Ners',
        'Siska Roheni, A.Md.Kep',
        'Hilya Aeni, A.Md.Kep',
        'Dea Agustin, A.Md.Kep',
        'Alvin Aprilianto Widjojo, A.Md.Kep',
        'Benny Laksana, A.Md.Kep',
        'Hemavanna Trisrasepti, A.Md.Kep',
        'Dedeh Rina, A.Md.Kep',
        'Miftah Choirul Anam, S.Kep.,Ners',
        'Candra Nugraha, A.Md.Kep',
        'Ecin Lestari Putri, A.Md.Kep',
    ],

    'tujuanUnitsIpsrs' => [
        'Maintenance',
        'Kesehatan Lingkungan',
        'Elektromedis (Atem)',
    ],

    'tujuanUnitsOutsourcing' => [
        'SJS',
        'Laundry',
        'Security ATALIAN',
        'Parkir Berlian',
        'Tata Graha (Taman)',
    ],

    'ruang' => [
        'Ruang Meeting',
        'Ruang Diklat',
        'Ruang Komite Medik',
    ],

    'approval' => [
        'Approved',
        'Rejected',
        'Pending',
    ],

    'jenis_kendaraan' => [
        'Operational Xpander (Khusus Marketing)',
        'Operational Avanza',
        'Ambulance Alphard',
        'Ambulance Luxio',
        'Motor Vario',
    ],

    'jumlah_penumpang' => [
        '1 Orang',
        '2 Orang',
        '3 Orang',
        '4 Orang',
        '5 Orang',
        '6 Orang',
        '7 Orang',
    ],

    'waktu_tempuh' => [
        '1 Jam',
        '2 Jam',
        '3 Jam',
        '> 4 Jam',
    ],

    'jarak_tempuh' => [
        '1 Km',
        '2 Km',
        '3 Km',
        '4 Km',
        '5 Km',
        '6 Km',
        '7 Km',
        '8 Km',
        '9 Km',
        '> 10 Km',
    ],

    'jenis_layanan' => [
        'Dengan Driver',
        'Tanpa Driver',
    ],

    'tim' => [
        'Tim 1',
        'Tim 2',
    ],

    'dampak' => [
        '1' => '1',
        '2' => '2',
        '3' => '3',
        '4' => '4',
        '5' => '5',
    ],

    'kemungkinan' => [
        '1' => '1',
        '2' => '2',
        '3' => '3',
        '4' => '4',
        '5' => '5',
    ],

    'satuan' => [
        'px',
        'cm',
        'm',
        'inch',
    ],

    'toner' => [
        'BROTHER HL-L2360DN',
        'BROTHER HL-B2080DW',
        'EPSON M1140',
        'EPSON L6550 - MAGENTA',
        'EPSON L6550 - YELLOW',
        'EPSON L6550 - BLACK',
        'EPSON L6550 - CYAN',
    ],
];
