<?php

return [
    'units' => [
        'Admisi dan Billing',
        'Akuntansi',
        'Casemix',
        'CSSD',
        'Direktur RS',
        'Dokter',
        'Farmasi',
        'Fisioterapi',
        'Gudang',
        'Gizi',
        'HD',
        'ICU',
        'IT',
        'Kanit',
        'Keuangan',
        'Kesehatan Lingkungan',
        'Komite Medik',
        'Komite Mutu',
        'Laboratorium',
        'Maintenance',
        'Manager',
        'Marketing',
        'NICU dan PICU',
        'NS Poli',
        'OK',
        'Pengadaan',
        'Perawat',
        'Radiologi',
        'Rawat Inap',
        'Rekam Medis',
        'SDM',
        'Security',
        'Sekretaris',
        'SPV',
        'UGD',
        'VK',
    ],

    'spo' => [
        'Asuhan Mutu',
        'Dept. Casemix',
        'Dept. Pelayanan Medis',
        'Dept. Penunjang Medis',
        'Dialisis',
        'Div. Akuntansi',
        'Div. HLC',
        'Div. Hukum & HI',
        'Div. Keuangan',
        'Div. SDM & Diklat',
        'Div. Teknologi Informasi',
        'Duty Manajer',
        'Farmasi',
        'Gizi',
        'IGD',
        'Intensif',
        'Kamar Operasi & CSSD',
        'Komite Etik & Hukum',
        'Komite Farmasi Terapi',
        'Komite K3RS',
        'Komite Keperawatan',
        'Komite Medik',
        'Komite Mutu',
        'Komite Nakes Lain',
        'Komite PPRA',
        'Komite PPI',
        'Laboratorium',
        'Layanan Pelanggan',
        'Logistik & Pengembangan',
        'Pemasaran',
        'Pemeliharaan',
        'Pengadaan & Aset',
        'Poliklinik',
        'Radiologi',
        'Rawat Inap',
        'Rehabilitasi Medik',
        'Rekam Medik',
        'Ruang Bersalin',
        'Tata Graha',
    ],

    'utw' => [
        'Admisi',
        'Admisi JKN',
        'Ahli Gizi',
        'Analis Kesehatan & Laboratorium',
        'Apoteker',
        'Bendahara',
        'Bidan',
        'Bidan - VK',
        'Billing',
        'Call Center',
        'Customer Service',
        'Divisi Asuhan & Mutu Keperawatan',
        'Divisi HLC',
        'Divisi Logistik & Pengembangan SDM Keperawatan',
        'Driver',
        'Fisioterapi',
        'Gudang Farmasi',
        'Helper',
        'Jasa Medis',
        'Kanit Admisi Billing',
        'Kanit Analis Kesehatan & Laboratorium',
        'Kanit Gizi',
        'Kanit HD',
        'Kanit IGD',
        'Kanit Intensif',
        'Kanit Kamar Operasi & CSSD',
        'Kanit Pemeliharaan',
        'Kanit Pengadaan & Aset',
        'Kanit Poliklinik',
        'Kanit Radiologi',
        'Kanit Rawat Inap',
        'Kanit Rekam Medis',
        'Kanit Rehabilitasi Medik',
        'Kanit Ruang Bersalin (VK)',
        'Kanit Tata Graha',
        'Manajer Casemix',
        'Manajer Keperawatan',
        'Manajer Keuangan & Akuntansi',
        'Manajer Pemasaran & Layanan Pelanggan',
        'Manajer Pelayanan Medis',
        'Manajer Penunjang Medis',
        'Manajer SDM & Hukum',
        'Manajer Umum',
        'Operasional IT',
        'Operator Teknisi MEP',
        'Penagihan & Tarif',
        'Perawat Gigi atau Terapis Gigi',
        'Perawat HD',
        'Perawat IGD',
        'Perawat Intensif (ICU)',
        'Perawat NICU & PICU',
        'Perawat OK',
        'Perawat Poliklinik',
        'Perawat Rawat Inap',
        'Radiografer',
        'Refraksi Optical',
        'Rekam Medis',
        'SPV Akuntansi',
        'SPV Farmasi',
        'SPV Keuangan',
        'SPV Layanan Pelanggan',
        'SPV Pelayanan Mutu & JKN',
        'SPV Pemasaran',
        'SPV Rawat Inap',
        'SPV Rawat Jalan',
        'SPV SDM & Hukum',
        'SPV Teknologi Informasi',
        'SPV Umum',
        'Staf Beban & Hutang Dagang',
        'Staf Bimroh & Pemulasaran Jenazah',
        'Staf Diklat',
        'Staf Elektromedis',
        'Staf Hukum',
        'Staf JKN',
        'Staf Pendapatan, Piutang, Asset & Persediaan',
        'Staf Pengadaan',
        'Staf Penjualan',
        'Staf SDM',
        'Staf Verifikasi, Anggaran, Pajak',
        'Sterilisasi CSSD',
        'Terapis Wicara',
        'Tenaga Teknik Kefarmasian',
        'Transporter Rekam Medis',
    ],

    'sk' => [
        'Penunjukan Petugas MOD',
        'Penunjukan Koordinator MOD',
        'Penunjukan Pengurus P2K3',
        'Penunjukan Ahli K3',
        'Kementerian Penunjukan Dokter P2K3',
        'Kementerian Ahli K3',
        'Pembentukan PIC Layanan JKN',
        'Penunjukan PIC Portal Informasi Faskes Layanan JKN',
        'Penunjukan Pejabat Pengadaan (PP) dan Pejabat Pembuat Komitmen (PPK)',
        'Dokter PJ Anestesi IBS, CSSD, dan Rawat Intensif',
        'Dokter PJ Unit Laboratorium',
        'Dokter PJ Unit Radiologi',
        'Penunjukan Clinical Instructor (CI) Keperawatan',
        'Penunjukan SPGDT (Sistem Penanggulangan Gawat Darurat Terpadu)',
        'Manajer Pemasaran dan Layanan Pelanggan',
        'Manajer Pelayanan Medis',
        'Manajer Keuangan dan Akuntansi',
        'Manajer Umum',
        'Manajer Casemix',
        'PJS Manajer Penunjang Medis',
        'PJS Manajer Keperawatan',
        'SPV SDM dan Hukum',
        'SPV Keuangan',
        'SPV Akuntansi',
        'SPV Umum',
        'SPV Penjualan',
        'SPV Layanan Pelanggan',
        'SPV Rawat Jalan',
        'SPV Rawat Inap',
        'SPV Farmasi',
        'SPV IT',
        'SPV Pelayanan dan Mutu JKN',
        'SPV Pelayanan dan Mutu JKN',
        'PJS SPV Logistik dan Pengembangan SDM Keperawatan',
        'Kanit Poli',
        'Kanit OK',
        'Kanit Gizi',
        'Kanit Tata Graha',
        'Kanit Pengadaan dan Aset',
        'Kanit Rawat Inap',
        'Kanit HD',
        'Kanit Admisi & Billing',
        'Kanit Pemeliharaan',
        'Kanit Laboratorium',
        'Kanit Radiologi',
        'Kanit Rekam Medis',
        'Kanit IGD',
        'PJS Kanit Rehabilitasi Medik',
        'Tunjangan Di Luar Jam Kerja',
        'Sanksi Disiplin Pelanggaran Karyawan',
        'Ketentuan Jam Besuk Rawat Inap',
    ],

    'komite_medik' => [
        'PPK - KSM Anak',
        'PPK - KSM Anestesi',
        'PPK - KSM Bedah',
        'PPK - KSM Gigi',
        'PPK - KSM Jantung',
        'PPK - KSM Kulit',
        'PPK - KSM Obgyn',
        'PPK - KSM Paru',
        'PPK - KSM Penunjang',
        'PPK - KSM Penyakit Dalam',
        'PPK - KSM Saraf',
        'Clinical Pathway - KSM Anak',
        'Clinical Pathway - KSM Anestesi',
        'Clinical Pathway - KSM Bedah',
        'Clinical Pathway - KSM Gigi',
        'Clinical Pathway - KSM Jantung',
        'Clinical Pathway - KSM Kulit',
        'Clinical Pathway - KSM Obgyn',
        'Clinical Pathway - KSM Paru',
        'Clinical Pathway - KSM Penunjang',
        'Clinical Pathway - KSM Penyakit Dalam',
        'Clinical Pathway - KSM Saraf',
    ],

    'perawat' => [
        'Yusuf Ifnugroho, AMK">Yusuf Ifnugroho, AMK',
        'Nur Fitriyana Sutisna, S.Kep.,Ners',
        'Siska Roheni, A.Md.Kep',
        'Hilya Aeni, A.Md.Kep',
        'Dea Agustin, A.Md.Kep',
        'Alvin Aprilianto Widjojo, A.Md.Kep',
        'Benny Laksana, A.Md.Kep',
        'Hemavanna Trisrasepti, A.Md.Kep',
        'Dedeh Rina, A.Md.Kep',
        'Miftah Choirul Anam, S.Kep.,Ners',
        'Candra Nugraha, A.Md.Kep',
        'Ecin Lestari Putri, A.Md.Kep',
    ],

    'tujuanUnitsIpsrs' => [
        'Maintenance',
        'Kesehatan Lingkungan',
        'Elektromedis (Atem)',
    ],

    'tujuanUnitsOutsourcing' => [
        'SJS',
        'Laundry',
        'Security ATALIAN',
        'Parkir Berlian',
        'Tata Graha (Taman)',
    ],

    'ruang' => [
        'Ruang Meeting',
        'Ruang Diklat',
        'Ruang Komite Medik',
    ],

    'approval' => [
        'Approved',
        'Rejected',
        'Pending',
    ],

    'jenis_kendaraan' => [
        'Operational Xpander (Khusus Marketing)',
        'Operational Avanza',
        'Ambulance Alphard',
        'Ambulance Luxio',
        'Motor Vario',
    ],

    'jumlah_penumpang' => [
        '1 Orang',
        '2 Orang',
        '3 Orang',
        '4 Orang',
        '5 Orang',
        '6 Orang',
        '7 Orang',
    ],

    'waktu_tempuh' => [
        '1 Jam',
        '2 Jam',
        '3 Jam',
        '> 4 Jam',
    ],

    'lantai' => [
        'Lantai 1',
        'Lantai 2',
        'Lantai 3',
        'Lantai 4',
        'Lantai 5',
    ],

    'jarak_tempuh' => [
        '1 Km',
        '2 Km',
        '3 Km',
        '4 Km',
        '5 Km',
        '6 Km',
        '7 Km',
        '8 Km',
        '9 Km',
        '> 10 Km',
    ],

    'jenis_layanan' => [
        'Dengan Driver',
        'Tanpa Driver',
    ],

    'tim' => [
        'Tim 1',
        'Tim 2',
    ],

    'dampak' => [
        '1' => '1',
        '2' => '2',
        '3' => '3',
        '4' => '4',
        '5' => '5',
    ],

    'kemungkinan' => [
        '1' => '1',
        '2' => '2',
        '3' => '3',
        '4' => '4',
        '5' => '5',
    ],

    'satuan' => [
        'px',
        'cm',
        'm',
        'inch',
    ],

    'toner' => [
        'BROTHER HL-L2360DN',
        'BROTHER HL-B2080DW',
        'EPSON M1140',
        'EPSON L6550 - MAGENTA',
        'EPSON L6550 - YELLOW',
        'EPSON L6550 - BLACK',
        'EPSON L6550 - CYAN',
    ],
];
